- name: checking service status
  hosts: WS
  tasks:
  - name: checking service status
    command: systemctl status "{{ item }}"
    with_items:
    - httpd
    register: result
    ignore_errors: yes